/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const LeaderboardEntry = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'workoutCount' : IDL.Nat,
  'memberSince' : Time,
});
export const NotificationPreferences = IDL.Record({
  'mealReminders' : IDL.Bool,
  'userId' : UserId,
  'reminderTime' : IDL.Text,
  'hydrationReminders' : IDL.Bool,
  'workoutReminders' : IDL.Bool,
});
export const OnboardingData = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'trainingExperience' : IDL.Text,
  'activityLevel' : IDL.Text,
  'primaryGoal' : IDL.Text,
  'stressLevel' : IDL.Text,
  'userId' : UserId,
  'preferredWorkoutDuration' : IDL.Text,
  'secondaryGoal' : IDL.Text,
  'dietType' : IDL.Text,
  'foodAllergies' : IDL.Text,
  'mealsPerDay' : IDL.Nat,
  'availableDaysPerWeek' : IDL.Nat,
  'biologicalSex' : IDL.Text,
  'sleepDuration' : IDL.Float64,
});
export const ProgressEntry = IDL.Record({
  'chestCm' : IDL.Float64,
  'userId' : UserId,
  'date' : IDL.Text,
  'hipsCm' : IDL.Float64,
  'weightKg' : IDL.Float64,
  'notes' : IDL.Text,
  'armsCm' : IDL.Float64,
  'waistCm' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'verificationCode' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'lastName' : IDL.Text,
  'hasCompletedOnboarding' : IDL.Bool,
  'firstName' : IDL.Text,
});
export const WorkoutLog = IDL.Record({
  'userId' : UserId,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'weightKg' : IDL.Float64,
  'notes' : IDL.Text,
  'exerciseName' : IDL.Text,
  'muscleGroup' : IDL.Text,
  'loggedAt' : Time,
});

export const idlService = IDL.Service({
  'checkEmailExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getNotificationPreferences' : IDL.Func(
      [],
      [IDL.Opt(NotificationPreferences)],
      ['query'],
    ),
  'getOnboardingData' : IDL.Func([], [IDL.Opt(OnboardingData)], ['query']),
  'getProgressEntries' : IDL.Func([], [IDL.Vec(ProgressEntry)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'getWorkoutLogsInRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(WorkoutLog)],
      ['query'],
    ),
  'logWorkout' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'markUserVerified' : IDL.Func([], [IDL.Bool], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'saveNotificationPreferences' : IDL.Func(
      [NotificationPreferences],
      [IDL.Bool],
      [],
    ),
  'saveOnboardingData' : IDL.Func([OnboardingData], [IDL.Bool], []),
  'saveProgressEntry' : IDL.Func([ProgressEntry], [IDL.Bool], []),
  'setVerificationCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateOnboardingCompletion' : IDL.Func([], [IDL.Bool], []),
  'updateUserProfile' : IDL.Func([UserProfile], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const LeaderboardEntry = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'workoutCount' : IDL.Nat,
    'memberSince' : Time,
  });
  const NotificationPreferences = IDL.Record({
    'mealReminders' : IDL.Bool,
    'userId' : UserId,
    'reminderTime' : IDL.Text,
    'hydrationReminders' : IDL.Bool,
    'workoutReminders' : IDL.Bool,
  });
  const OnboardingData = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'trainingExperience' : IDL.Text,
    'activityLevel' : IDL.Text,
    'primaryGoal' : IDL.Text,
    'stressLevel' : IDL.Text,
    'userId' : UserId,
    'preferredWorkoutDuration' : IDL.Text,
    'secondaryGoal' : IDL.Text,
    'dietType' : IDL.Text,
    'foodAllergies' : IDL.Text,
    'mealsPerDay' : IDL.Nat,
    'availableDaysPerWeek' : IDL.Nat,
    'biologicalSex' : IDL.Text,
    'sleepDuration' : IDL.Float64,
  });
  const ProgressEntry = IDL.Record({
    'chestCm' : IDL.Float64,
    'userId' : UserId,
    'date' : IDL.Text,
    'hipsCm' : IDL.Float64,
    'weightKg' : IDL.Float64,
    'notes' : IDL.Text,
    'armsCm' : IDL.Float64,
    'waistCm' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'verificationCode' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'lastName' : IDL.Text,
    'hasCompletedOnboarding' : IDL.Bool,
    'firstName' : IDL.Text,
  });
  const WorkoutLog = IDL.Record({
    'userId' : UserId,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'weightKg' : IDL.Float64,
    'notes' : IDL.Text,
    'exerciseName' : IDL.Text,
    'muscleGroup' : IDL.Text,
    'loggedAt' : Time,
  });
  
  return IDL.Service({
    'checkEmailExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getNotificationPreferences' : IDL.Func(
        [],
        [IDL.Opt(NotificationPreferences)],
        ['query'],
      ),
    'getOnboardingData' : IDL.Func([], [IDL.Opt(OnboardingData)], ['query']),
    'getProgressEntries' : IDL.Func([], [IDL.Vec(ProgressEntry)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'getWorkoutLogsInRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(WorkoutLog)],
        ['query'],
      ),
    'logWorkout' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'markUserVerified' : IDL.Func([], [IDL.Bool], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveNotificationPreferences' : IDL.Func(
        [NotificationPreferences],
        [IDL.Bool],
        [],
      ),
    'saveOnboardingData' : IDL.Func([OnboardingData], [IDL.Bool], []),
    'saveProgressEntry' : IDL.Func([ProgressEntry], [IDL.Bool], []),
    'setVerificationCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateOnboardingCompletion' : IDL.Func([], [IDL.Bool], []),
    'updateUserProfile' : IDL.Func([UserProfile], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };