/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry {
  'displayName' : string,
  'userId' : UserId,
  'workoutCount' : bigint,
  'memberSince' : Time,
}
export interface NotificationPreferences {
  'mealReminders' : boolean,
  'userId' : UserId,
  'reminderTime' : string,
  'hydrationReminders' : boolean,
  'workoutReminders' : boolean,
}
export interface OnboardingData {
  'age' : bigint,
  'weight' : number,
  'height' : number,
  'trainingExperience' : string,
  'activityLevel' : string,
  'primaryGoal' : string,
  'stressLevel' : string,
  'userId' : UserId,
  'preferredWorkoutDuration' : string,
  'secondaryGoal' : string,
  'dietType' : string,
  'foodAllergies' : string,
  'mealsPerDay' : bigint,
  'availableDaysPerWeek' : bigint,
  'biologicalSex' : string,
  'sleepDuration' : number,
}
export interface ProgressEntry {
  'chestCm' : number,
  'userId' : UserId,
  'date' : string,
  'hipsCm' : number,
  'weightKg' : number,
  'notes' : string,
  'armsCm' : number,
  'waistCm' : number,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'verificationCode' : string,
  'displayName' : string,
  'createdAt' : Time,
  'email' : string,
  'isVerified' : boolean,
  'passwordHash' : string,
  'lastName' : string,
  'hasCompletedOnboarding' : boolean,
  'firstName' : string,
}
export interface WorkoutLog {
  'userId' : UserId,
  'reps' : bigint,
  'sets' : bigint,
  'weightKg' : number,
  'notes' : string,
  'exerciseName' : string,
  'muscleGroup' : string,
  'loggedAt' : Time,
}
export interface _SERVICE {
  'checkEmailExists' : ActorMethod<[string], boolean>,
  'getLeaderboard' : ActorMethod<[string, bigint], Array<LeaderboardEntry>>,
  'getNotificationPreferences' : ActorMethod<
    [],
    [] | [NotificationPreferences]
  >,
  'getOnboardingData' : ActorMethod<[], [] | [OnboardingData]>,
  'getProgressEntries' : ActorMethod<[], Array<ProgressEntry>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWorkoutLogs' : ActorMethod<[], Array<WorkoutLog>>,
  'getWorkoutLogsInRange' : ActorMethod<[Time, Time], Array<WorkoutLog>>,
  'logWorkout' : ActorMethod<
    [string, string, bigint, bigint, number, string],
    boolean
  >,
  'loginUser' : ActorMethod<[string, string], boolean>,
  'markUserVerified' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'saveNotificationPreferences' : ActorMethod<
    [NotificationPreferences],
    boolean
  >,
  'saveOnboardingData' : ActorMethod<[OnboardingData], boolean>,
  'saveProgressEntry' : ActorMethod<[ProgressEntry], boolean>,
  'setVerificationCode' : ActorMethod<[string], boolean>,
  'updateOnboardingCompletion' : ActorMethod<[], boolean>,
  'updateUserProfile' : ActorMethod<[UserProfile], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];