/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OnboardingData {
    age: bigint;
    weight: number;
    height: number;
    trainingExperience: string;
    activityLevel: string;
    primaryGoal: string;
    stressLevel: string;
    userId: UserId;
    preferredWorkoutDuration: string;
    secondaryGoal: string;
    dietType: string;
    foodAllergies: string;
    mealsPerDay: bigint;
    availableDaysPerWeek: bigint;
    biologicalSex: string;
    sleepDuration: number;
}
export type UserId = Principal;
export interface WorkoutLog {
    userId: UserId;
    reps: bigint;
    sets: bigint;
    weightKg: number;
    notes: string;
    exerciseName: string;
    muscleGroup: string;
    loggedAt: Time;
}
export type Time = bigint;
export interface NotificationPreferences {
    mealReminders: boolean;
    userId: UserId;
    reminderTime: string;
    hydrationReminders: boolean;
    workoutReminders: boolean;
}
export interface LeaderboardEntry {
    displayName: string;
    userId: UserId;
    workoutCount: bigint;
    memberSince: Time;
}
export interface ProgressEntry {
    chestCm: number;
    userId: UserId;
    date: string;
    hipsCm: number;
    weightKg: number;
    notes: string;
    armsCm: number;
    waistCm: number;
}
export interface UserProfile {
    verificationCode: string;
    displayName: string;
    createdAt: Time;
    email: string;
    isVerified: boolean;
    passwordHash: string;
    lastName: string;
    hasCompletedOnboarding: boolean;
    firstName: string;
}
export interface backendInterface {
    checkEmailExists(email: string): Promise<boolean>;
    getLeaderboard(_period: string, topN: bigint): Promise<Array<LeaderboardEntry>>;
    getNotificationPreferences(): Promise<NotificationPreferences | null>;
    getOnboardingData(): Promise<OnboardingData | null>;
    getProgressEntries(): Promise<Array<ProgressEntry>>;
    getUserProfile(): Promise<UserProfile | null>;
    getWorkoutLogs(): Promise<Array<WorkoutLog>>;
    getWorkoutLogsInRange(startTime: Time, endTime: Time): Promise<Array<WorkoutLog>>;
    logWorkout(exerciseName: string, muscleGroup: string, sets: bigint, reps: bigint, weightKg: number, notes: string): Promise<boolean>;
    loginUser(email: string, passwordHash: string): Promise<boolean>;
    markUserVerified(): Promise<boolean>;
    registerUser(firstName: string, lastName: string, email: string, passwordHash: string, displayName: string): Promise<boolean>;
    saveNotificationPreferences(prefs: NotificationPreferences): Promise<boolean>;
    saveOnboardingData(data: OnboardingData): Promise<boolean>;
    saveProgressEntry(entry: ProgressEntry): Promise<boolean>;
    setVerificationCode(code: string): Promise<boolean>;
    updateOnboardingCompletion(): Promise<boolean>;
    updateUserProfile(profile: UserProfile): Promise<boolean>;
}
import type { NotificationPreferences as _NotificationPreferences, OnboardingData as _OnboardingData, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkEmailExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkEmailExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkEmailExists(arg0);
            return result;
        }
    }
    async getLeaderboard(arg0: string, arg1: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0, arg1);
            return result;
        }
    }
    async getNotificationPreferences(): Promise<NotificationPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationPreferences();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationPreferences();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnboardingData(): Promise<OnboardingData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingData();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingData();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressEntries(): Promise<Array<ProgressEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressEntries();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutLogs(): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutLogs();
            return result;
        }
    }
    async getWorkoutLogsInRange(arg0: Time, arg1: Time): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutLogsInRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutLogsInRange(arg0, arg1);
            return result;
        }
    }
    async logWorkout(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: number, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return result;
        }
    }
    async markUserVerified(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markUserVerified();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markUserVerified();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveNotificationPreferences(arg0: NotificationPreferences): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNotificationPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNotificationPreferences(arg0);
            return result;
        }
    }
    async saveOnboardingData(arg0: OnboardingData): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOnboardingData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOnboardingData(arg0);
            return result;
        }
    }
    async saveProgressEntry(arg0: ProgressEntry): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProgressEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProgressEntry(arg0);
            return result;
        }
    }
    async setVerificationCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setVerificationCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVerificationCode(arg0);
            return result;
        }
    }
    async updateOnboardingCompletion(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOnboardingCompletion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOnboardingCompletion();
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NotificationPreferences]): NotificationPreferences | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OnboardingData]): OnboardingData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
